---
# tasks file for rabi
- name: Install git
  apt: name=git state=latest
- name: Install docker
  apt: name=docker.io state=latest
- name: Install httpd
  apt: name=apache2 state=latest
- include_tasks: copy.yml
- include_tasks: create.yml
